## Study questions for Chapter 9 computer lab session ##

# Name:
# Date:

### Note that the tutorial that will explain most of the answers to these questions is
### here: https://markravinet.github.io/Chapter9.html

### INSTRUCTIONS ###
# The easiest way to submit your work is use this R script as a template. You should show
# your code. You should also show the answers using the hash (#) symbol to comment them
# out.
#
# When you are finished, you can click, File>Save_as and alter the extension of the script
# from .R to .txt - this will save it as a text file which you can then upload to Canvas.
# We recommend you do this last of all, because it will destroy the syntax highlighting in
# your R code.

# 1. How can you display the names of objects stored within a phylo object - i.e. the 
## random tree we created in the tutorial? 
## NB - ?phylo will help you find a description of what each object is

# 2. Draw a random tree with 23 taxa. Make it a radial tree, with an edge width of 1.5.
##   It must be any colour other than black. 

# 3. Extract the Proaves clade from the bird.orders dataset, plot it and also
## test whether ducks and gees (Anseriformes) and chickens and turkeys (Galliformes)
## are monophyletic.

# 4. Using the full primates dataset, calculate the pairwise distance matrix using the
##   most suitable sequence model and then construct both UPGMA and NJ trees. Then choose
##  an outgroup on the NJ tree and replot it. Which tree is most parsimonious? You should 
## calcualte the parsimony score for all three trees - i.e. UPGMA, NJ and NJ rooted. Also 
## can you explain the odd placement of the Bovine sequence on the tree?

# 5. Looking at the dogs genlight object we created, how man SNP markers are there? How many
##   individuals? Note that all these invidividuals are village dogs - what percentage of the 
##   markers and village dog individuals used in the original study are we dealing with here?

# 6. From the eigenvalues generated by our dogs_pca, how many principal components should we 
# #  consider to account for approximately 10% of the variance?

# 7. Draw the full village dogs PCA. Colour the points by location. Which is the most divergent
##  group on PC1? What proportion of the variance do the first two principal components explain?
